title: Raspberry Pi Audio(.mp3) Player
description: Great things coming soon...
theme: just-the-docs

url: https://ronphan22.github.io/just-the-doc-jekyll-document/ 

aux_links:
  Template Repository: https://github.com/RonPhan22/just-the-doc-jekyll-document/
