title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ronphan22.github.io/just-the-doc-jekyll-document/ 

aux_links:
  Template Repository: https://github.com/RonPhan22/just-the-docs-template
