title: TEJ3 Culmination
description: Great things coming soon...
theme: just-the-docs


name: Bao Khanh (Ron) Phan
project description: Use Raspberry Pi to play audio by embedding Python script and connecting wires. 

url: https://ronphan22.github.io/just-the-doc-jekyll-document/ 

aux_links:
  Template Repository: https://github.com/RonPhan22/just-the-doc-jekyll-document/
